name: Visitor Badge
description: Add a badge to count visitors for your issues and PRs.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication.
    required: true
  color:
    description: The color or the badge. You can use any valid HEX color or pick from a predefined set of named colors. Default is `blue`. Note that the HEX colors should be used without `#` symbol prefix.
    required: false
  style:
    description: The style of the badge. Support `flat`, `flat-square	`, `plastic`. Default is `flat`.
    required: false
  label:
    description: The label of the badge. Default is `'visitors'`.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: type
  color: blue # gray-dark purple red orange green blue yellow black white
